### ISSUE TITLE
Pass arguments to `Rule::evaluate` as a structure

### ISSUE THREAD

**Issue by KodrAus** [PolySync/cargo-culture#7]
This is just a suggestion based on a first impression. Please close this if you disagree!

It might be more ergonomic to write new `Rule`s and flexible to the addition of more arguments of the [`Rule::evaluate` metbod](https://github.com/PolySync/cargo-culture/blob/master/cargo-culture-kit/src/rules/mod.rs#L64-L70) accepted a single structure as an argument containing the path, flags, metadata etc. Maybe something like:

```rust
struct RuleContext<'a> {
    cargo_manifest_file_path: &'a Path,
    verbose: bool,
    metadata: Option<&'a Metadata>,
    print_output: &'a mut Write,
    ...
}

...

impl Rule for CargoMetadataReadable {
    fn evaluate(&self, ctxt: RuleContext) -> RuleOutcome {
        match ctxt.metadata() {
            None => RuleOutcome::Failure,
            Some(_) => RuleOutcome::Success,
        }
    }
}
```

What do you think?

**Comment by ZackPierce** [comment]
I think this is a good idea. The `evaluate` parameter count has gotten a bit high, and this would be good future-proofing against further optional expansions.

**Comment by ZackPierce** [comment]
Implemented by https://github.com/PolySync/cargo-culture/pull/8
